/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./src/components/AppBar.vue')['default']
    AppBarCopy: typeof import('./src/components/AppBarCopy.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    GameButton: typeof import('./src/components/GameButton.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LangSwitcher: typeof import('./src/components/LangSwitcher.vue')['default']
    MapBackground: typeof import('./src/components/MapBackground.vue')['default']
    MapGpsControls: typeof import('./src/components/MapGpsControls.vue')['default']
    MapZoomControls: typeof import('./src/components/MapZoomControls.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterTile: typeof import('./src/components/RouterTile.vue')['default']
    RouterTileCopy: typeof import('./src/components/RouterTileCopy.vue')['default']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
